name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3
      with:
        version: 8
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright Browsers
      working-directory: ./apps/frontend
      run: pnpm exec playwright install --with-deps

    - name: Run Playwright tests
      working-directory: ./apps/frontend
      run: pnpm exec playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: apps/frontend/playwright-report/
        retention-days: 30
